### ISSUE TITLE
when element === nil this line throws TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by tevel** [schema-inspector/schema-inspector#119]
https://github.com/schema-inspector/schema-inspector/blob/af0ea2762525bf3bfe086ab9ddd3be0229dafcf5/lib/schema-inspector.js#L141

Offered solution: change the order of conditions in this line.

**Comment by tevel** [comment]
the correct order should be: 
`return typeof element === 'object' && element != null && element.constructor !== Array; `

**Comment by mattwelke** [comment]
Ah the joys of JS.

![image](https://user-images.githubusercontent.com/7719209/116578450-6b853f00-a8df-11eb-811b-17fcd4537ae3.png)
![image](https://user-images.githubusercontent.com/7719209/116578459-6f18c600-a8df-11eb-8d9a-66a73403b65a.png)

**Comment by tevel** [comment]
the problem is it fails with TypeError: Cannot read property 'constructor' of null

**Comment by stemwinder** [comment]
Ran in to this in the upgrade from 2.0.0 to 2.0.1. Downgrading resolves the issue (for now).
