### ISSUE TITLE
Provide a global strict option

### ISSUE THREAD

**Issue by danwkennedy** [schema-inspector/schema-inspector#45]
Instead of requiring each object set it's strict option, it'd be handy to just have a global type strict option. Most of the time, if I want one of my object rules to be strict, I want them all to be strict.

**Comment by mattwelke** [comment]
@danwkennedy Do you think this feature would still be useful for you?

**Comment by danwkennedy** [comment]
@mattwelke I believe it'd still be useful, however, I've since left the company that uses this package. Thank you for following up though! It's good to see this project getting some love :)

**Comment by mattwelke** [comment]
Thanks for responding. "Love" is subjective. It's an old library from before the new JSON Schema standards. But I've for some reason agreed to maintain it. :P

I'll close this, and people can reopen it if there's a need for the feature.

**Comment by Yash-Singh1** [comment]
I think this could be a useful option because it could prevent me from writing `strict: true`, every time.

**Comment by mattwelke** [comment]
> I think this could be a useful option because it could prevent me from writing strict: true, every time.

We're going to move forward with a maintenance only approach for this library. We'll look for "would", not "could". If someone currently using it has a specific use case for a desired feature, we'd take it on. But we wouldn't add features for the sake of trying to grow the userbase, which isn't a goal right now.
