### ISSUE TITLE
Error details?

### ISSUE THREAD

**Issue by mbt-jeremy-r** [schema-inspector/schema-inspector#56]
Following #54 , it may be a good idea to provide some details about the error.

As a example of the need, I am using my own error system, and want to translate schema-inspector errors to my system. 
If I receive a `type` error, and want to log the expected/received types, I need to parse the `message` property, which may change in the future, breaking the parsing.

The proposed feature is a object/array giving thoses details along with the reason. That object/array can change depending on the `reason` to fit each specific need.

The proposed fields are:

| reason | field(s) |
|--------|--------|
| type | expected_type, received_type |
| optional | |
| uniqueness | indexes |
| pattern | wrong_var, regex |
| minLength, maxLength, exactLength | expected_length, received_length |
| lt, lte, gt, gte, eq, ne | expected_value, received_value |
| someKeys | missing_keys |
| strict | unexpected_keys |

They are basically the variables you put in the `message` property, so it shouldn't be a great change, and would improve the usability of the module.

**Comment by mattwelke** [comment]
@mbt-jeremy-r Do you think this feature would still be useful for you?
