### ISSUE TITLE
Request: Add either access to all values or ability to set error property

### ISSUE THREAD

**Issue by TeemuKoivisto** [schema-inspector/schema-inspector#64]
Hello,

I have enjoyed using schema-inspector for my backend validation for a while and now I have tried using it in my React frontend.

The problem is however that I have two values that are dependent of each other. Say password and passwordConfirmation fields. The way to validate that they are equal is currently to pass an exec-handler and report the error to the root property "@". What I am requesting for is a way to either access the whole tree from passwordConfirmation exec-handler eg. `exec(schema, value, allValues) {` or ability to report the error to specific property eg. `this.report("Passwords must match", null, "equality", "@.passwordConfirmation")`.

I personally would rather just pass the originally given input as third parameter to exec-function as it makes the schema look clearer.

With backend validation it wasn't that important to have correct properties on the errors but with frontend forms it sucks to not have the errors on the correct property for rendering them with the right input.

**Comment by ViniciusFXavier** [comment]
Hello @TeemuKoivisto, you can use `this.origin` inside the `exec` to access all the values:
```js
{
	type: "object",
	properties: {
		password: {
			type: "string",
			optional: false
		},
		passwordConfirmation: {
			type: "string",
			optional: false,
			exec: function (schema, value) {
				// You can use 'this.origin' to access all the values
				if (this.origin.password !== value) {
					this.report('The passwords do not match', null, 'passwordConfirmation');
				}
			}
		}
	}
}
```
Result:
![image](https://user-images.githubusercontent.com/40774281/106832693-e5a38000-6670-11eb-9d9b-863172230dc4.png)

**Comment by ViniciusFXavier** [comment]
Feel free to reopen the issue if you think it is necessary.
