### ISSUE TITLE
Escape < > ' " & in to  &lt; &gt; &#39; &quot; &amp;

### ISSUE THREAD

**Issue by brahmos** [schema-inspector/schema-inspector#66]
Is it possible to do that today, without adding a new rule?

**Comment by mattwelke** [comment]
@brahmos 
Yep, you'd use the "exec" functionality to do custom sanitization. But I'd have to double check whether exec functions can be combined with official rules. I've never used that feature. And it might be worth having features like this as official rules too.

**Comment by Yash-Singh1** [comment]
> Is it possible to do that today, without adding a new rule?

```js
SchemaInspector.sanitize({
  exec: function (schema, post) {
    if (typeof post === 'string') {
      return post.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('\'', '&#39;').replace('"', '&quot;')
    } else {
      return post
    }
  }
}, '  <p>discussion about \'this\' & "that"</p> ')
```

> But I'd have to double check whether exec functions can be combined with official rules.

```js
SchemaInspector.sanitize({
  exec: function (schema, post) {
    if (typeof post === 'string') {
      return this.rules({ rules: ['trim', 'upper'] }, post)
    } else {
      return post
    }
  }
}, '  a b c ')
```

> And it might be worth having features like this as official rules too.

Yes, there should be a rule for URL encoding and XML escaping

**Comment by mattwelke** [comment]
Not stale. I'll be looking at these outstanding PRs soon.
