### ISSUE TITLE
Validation on object with integer key?

### ISSUE THREAD

**Issue by cention-sany** [schema-inspector/schema-inspector#67]
```
{
  1: {name: "test"},
  2: {name: "test2"}
}
```
Possible?

**Comment by ViniciusFXavier** [comment]
Yes, is possible.

![image](https://user-images.githubusercontent.com/40774281/106830739-6f514e80-666d-11eb-8216-1fb29c335c4e.png)
Try your self here: http://schema-inspector.github.io/schema-inspector/

**Comment by ViniciusFXavier** [comment]
Feel free to reopen the issue if you think it is necessary.
