### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by kalu111** [schema-inspector/schema-inspector#69]
Hi, 
It would be nice to have a typings for TypeScript projects :)

**Comment by mattwelke** [comment]
Now that I'm a maintainer of this repo, either converting to TypeScript so that typings are generated in repo, or manually creating typing files is something I can tackle soon if there's demand for it. I'll review a PR for this if anyone else implements it too.

**Comment by mattwelke** [comment]
This isn't considered a "won't do" but it will be a lot of work, so we'll be putting this off for a while.

**Comment by mattwelke** [comment]
Until further notice, this won't be done. Because the library is in maintenance mode (no new features, just bug fixes and security vulnerability patches), we won't be adding typings. We'll rely on the community to provide them via the DefinitelyTyped project if they want to.
