### ISSUE TITLE
Question: How to use multiple type options

### ISSUE THREAD

**Issue by 0Ams** [schema-inspector/schema-inspector#70]
```
var inspector = require('schema-inspector');
 
function Class() {}
 
var schema = {
    type: 'object',
    properties: {
        lorem: {  type: 'number' },
        ipsum: { type: 'any' },
        dolor: { type: ['number' 'string', 'null'] },
        sit: { type: Class }
    }
};
```
[rink](https://www.npmjs.com/package/schema-inspector#validation-1)
I would like to know how to use the multiple type of reference document.

For example, if I specify dolor type ['number', 'string'], `number` is min and max, and `string` is maxLength and minLength.
How to use multiple options type? 

Please let me know if this is possible 😭

**Comment by ViniciusFXavier** [comment]
Hello @0Ams the only way to do it is using `exec` and doing your own custom validation.

for more information: https://github.com/schema-inspector/schema-inspector#exec

**Comment by ViniciusFXavier** [comment]
**Validation example:**

Scheema: 
```js
{
	type: "object",
	properties: {
		name: {
			type: ["string", "number", "null"],
			exec: function (schema, value) {
				var stringMaxLength = 2;
				var numberMax = 1;
				if (typeof value === 'string' && value.length >= stringMaxLength) {
					this.report('must be shorter than ' + stringMaxLength + ' elements, but it has ' + value.length, null, 'maxLength');
				} else if (typeof value === 'number' && value > numberMax) {
				  this.report('must be at most ' + numberMax + ', but is ' + value, null, 'max');
				}
			}
		}
	}
}
```

Results:
- `number`
```js
{
  dolor: 100 // Property @.dolor: must be at most 1, but is 100
}
```
- `string`
```js
{
  dolor: "schema-inspector" // Property @.dolor: must be shorter than 2 elements, but it has 16
}
```

**Comment by ViniciusFXavier** [comment]
> ```
> var inspector = require('schema-inspector');
>  
> function Class() {}
>  
> var schema = {
>     type: 'object',
>     properties: {
>         lorem: {  type: 'number' },
>         ipsum: { type: 'any' },
>         dolor: { type: ['number' 'string', 'null'] },
>         sit: { type: Class }
>     }
> };
> ```
> 
> [rink](https://www.npmjs.com/package/schema-inspector#validation-1)
> I would like to know how to use the multiple type of reference document.
> 
> For example, if I specify dolor type ['number', 'string'], `number` is min and max, and `string` is maxLength and minLength.
> How to use multiple options type?
> 
> Please let me know if this is possible 😭

You can use do something like this:
```js
{
    type: 'object',
    properties: {
        lorem: {  type: 'number' },
        ipsum: { type: 'any' },
        dolor: {
            type: ['number' 'string', 'null'],
            minLength: 1, maxLength: 1000, // Only applies to string
            gt: 100, lt: 1 // Only applies to numbers
        },
        sit: { type: Class }
    }
}
```

**Comment by ViniciusFXavier** [comment]
Feel free to reopen the issue if you think it is necessary
