### ISSUE TITLE
Old URL redirect to not found page

### ISSUE THREAD

**Issue by ViniciusFXavier** [schema-inspector/schema-inspector#88]
![image](https://user-images.githubusercontent.com/40774281/106671604-8587dd80-658d-11eb-85cf-c81e710ecf62.png)

- Broken URL: http://atinux.github.io/schema-inspector/
- Change to:  http://schema-inspector.github.io/schema-inspector/

---

- Broken images
![image](https://user-images.githubusercontent.com/40774281/106671947-03e47f80-658e-11eb-9332-78d69b5770d6.png)

**Comment by mattwelke** [comment]
@ViniciusFXavier I took over ownership of this repo a few weeks ago and I have a few cleanup tasks to do because of it. This is one of those things. Thanks for the PR! I'll take a look at it soon, likely this weekend.
