### ISSUE TITLE
GHSL-2020-358: seeking security contact for your project

### ISSUE THREAD

**Issue by anticomputer** [schema-inspector/schema-inspector#90]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2020-358) in your project (Atinux/schema-inspector). We are approaching 90 days since our initial report and as per our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy), we intend to publish a public advisory detailing this issue. If you wish to discuss or further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2020-358 and we would love to help you resolve these issues. If not, feel free to close this issue and we will proceed with advisory publication on expiration.

**Comment by mattwelke** [comment]
Hi, this is a library I signed on to maintain when the original creator said he had too much of his plate to deal with the vulnerability. Since then, I experienced burnout and had to take some time off. I'm planning on getting back on this this weekend. I'll contact someone at that email if I need help. Thanks!

**Comment by anticomputer** [comment]
> Hi, this is a library I signed on to maintain when the original creator said
> he had too much of his plate to deal with the vulnerability. Since then, I
> experienced burnout and had to take some time off. I'm planning on getting
> back on this this weekend. I'll contact someone at that email if I need
> help. Thanks!
>

Sounds good, and no rush, we'll look for any questions/concerns you might have.
