### ISSUE TITLE
Package error in browsers

### ISSUE THREAD

**Issue by ottonielmatheus** [schema-inspector/schema-inspector#93]
An export problem that occurs when using the package by bower in the browser makes it useless to use it in browsers.

![image](https://user-images.githubusercontent.com/37461352/111466548-342d4b00-8702-11eb-9c92-00ab08e9c8c6.png)
![image](https://user-images.githubusercontent.com/37461352/111466568-38f1ff00-8702-11eb-8ebe-741d20c1609b.png)

**Comment by ViniciusFXavier** [comment]
How to reproduce the error:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <script type="text/javascript" src="https://rawgit.com/caolan/async/master/dist/async.js"></script>
    <script type="text/javascript" src="https://rawgit.com/atinux/schema-inspector/master/index.js"></script>
  </head>

  <body>
    <h1>Schema Inspector</h1>
  </body>
</html>
```

**Comment by ottonielmatheus** [comment]
### How to solve in Bower:

An alternative to work around the problem in **bower**, is to use bower overrides in `bower.json`.

![image](https://user-images.githubusercontent.com/37461352/111504514-808a8200-8726-11eb-8cbc-09c35d9c0c81.png)

This solves the problem with the package's `index.js`, without the need for changes ;)
